### ISSUE TITLE
2016 and 2017 events intermingled (duplicate events)

### ISSUE THREAD

**Issue by brendanarciszewski** [JustDerek1/FRCCentralIssues#17]
On the events tab, under the 2016 header, 2017 events are shown too.

The Greater Toronto Central Regional (2016) does not show. ONT District - Victoria Park Collegiate (2017) shows twice.
![img_0545](https://cloud.githubusercontent.com/assets/20262406/20504359/f3bf410e-b014-11e6-8688-9308bfba1a00.JPG)

As an addition, it would be nice to search only a certain year for events.

**Comment by bdarci** [comment]
*Greater Toronto Central, not Greater Toronto West

**Comment by JustDerek1** [comment]
That is not good.  So, when you initially loaded the app, did it crash upon loading the first time or during the setup?  I'm wondering if it triggered a second loading by accident.

**Comment by brendanarciszewski** [comment]
It has crashed a few times in regards loading an event (I was going to create a report but got sidetracked—I'll find time tomorrow), but not during initial app load, not once.

**Comment by JustDerek1** [comment]
Ok, I am going to look for how it could load more than once, but I think ultimately, I am just going to do a check to make sure that events are not loaded more than once as I am adding them to the internal database.  Thanks for getting back to me on this!

**Comment by JustDerek1** [comment]
This is now fixed in the next version.  You will need to delete the app and reinstall to have it reload the events.

**Comment by brendanarciszewski** [comment]
ONT District - Nipissing, ONT District - Windsor Essex, ONT District - Victoria Park, ONT District - Western (all 2017) are all still duplicated for me after deleting the app several times. I'll just wait for the next version, though. 

Greater Toronto West (2016) doesn't show up in event search (although it did once when I deleted the app), but it does show in the team view if the team attended (ie. 781).

**Comment by JustDerek1** [comment]
Brendan,

Ok, I will open this back up. I will need to dig a bit deeper on this one. So, it is only select events that are duplicate, correct?

Derek

**Comment by JustDerek1** [comment]
Duplicates are still showing for Brendan.

**Comment by JustDerek1** [comment]
I am seeing this with those events only now.  Very interesting.

**Comment by JustDerek1** [comment]
Ok, this is an odd data issue.  FIRST changed the event codes from one year to the next.  This is resulting in some odd results as they changed the event code **retroactively** - meaning that when they changed it for 2017, it also was applied to 2016.  Still looking into this.

**Comment by JustDerek1** [comment]
Ok, I ended up deleting event data and reloading it from FIRST.  The event codes were a different issue.  (One that I was aware of, but nobody had found yet.)  This was a different issue.  It _**should**_ be fixed now.  Please test it and let me know.  You should not need to delete your app and reload.  I was able to simply go into the app and it loaded the correct events.

**Comment by brendanarciszewski** [comment]
I did notice that the event code for GTR Central got changed to ONTO2 - I think (though I may be wrong) that it was ONTO1. ONTO2 for 2017 became Victoria Park.
Anyway, I am seeing all events and no duplicates now, so I would say the issue is fixed.

**Comment by JustDerek1** [comment]
Ok, cool.  If it comes up again, let me know.
