### ISSUE TITLE
Week #s for Stats

### ISSUE THREAD

**Issue by brendanarciszewski** [JustDerek1/FRCCentralIssues#26]
Under Foul Analysis 2016, Week #s start at 12 and make some curious jumps (ie. Week 18 to Week 28). Meanwhile, under Tower Captures per Week, Week #s run from 0-12. 
(Would those upper #s be offseason events?)

**Comment by JustDerek1** [comment]
So, I debated on this.  Week 0 through 12 represent consecutive weeks of competition and don't really tell you anything about the date.  The set that jumps numbers does it based on the calendar week.  So, there were events post-season in week 28.

I think that I could label the weeks by the first date in that week as well.  

Thoughts on what would be better?

**Comment by brendanarciszewski** [comment]
What about a hybrid approach? For official events, label them how FIRST labels them, but then after that, label them by week of the year.

**Comment by JustDerek1** [comment]
Ok, check out the Foul Analysis 2016.  I now have "Week", "Calendar Week" and "Week Start".  Those are the basic 3 options.  I could include all, two or just 1 of those columns.  Thoughts?

**Comment by JustDerek1** [comment]
(By the way, you should not have to reload the app to test that.  It pulls it from the server each time.

**Comment by brendanarciszewski** [comment]
You seem to have mingled 2016 and 2017 dates in the Week Start column.
Overall, it is much more clear. However, I would suggest leaving the Week entry blank if it is an off season event (any event in May or beyond), since it is confusing to look at (skipping 10 calendar weeks to advance 1 week doesn't seem right).
Also, there are a lot of off season events missing - am I correct in assuming that is because you have entered this data manually?

**Comment by JustDerek1** [comment]
No, I definitely do not manually enter data.  Or manually pull the data.  That would be a full time job!  I have jobs scheduled and scripts that are run that pull the data for me from both FIRST and The Blue Alliance.

The reason you are not seeing off season events, is that FIRST only supports some of the off season events.  I only get a couple data points from The Blue Alliance, such as photos.  TBA seems to have a better source for off season data.  It might be a future thing for me to pull more from the Blue Alliance and less directly from FIRST.

**Comment by JustDerek1** [comment]
Ha!  I need to figure out why there is any 2017 data in those calculations.  There haven't been any 2017 events!

**Comment by JustDerek1** [comment]
Ok, that the year being 2017 is now corrected.  Everything should be go there.  Thank you for digging into this one with me! 

Also, I removed the week indicator for off season weeks.

**Comment by brendanarciszewski** [comment]
You seem to have lost a week; I recall it starting 5/1/2016.
Also, Towers Captured per Week does not reflect this change.

**Comment by JustDerek1** [comment]
The dates were off.  So, I believe they should be correct now.  It shouldn't start at 5/1/2016 - that's close to the end of the season.

I applied it to the Towers Captured now as well.
