### ISSUE TITLE
Restricted access to specific match points

### ISSUE THREAD

**Issue by Jpatterson780** [JustDerek1/FRCCentralIssues#30]
The specific match details (2016 - auto crossings, boulder points, tower status) are only available when accessed through the team tab, the similarities in the way information is displayed would lead me to believe that information should also be available in the event tab. As an added bonus, this functionality makes the app an perfect tool for FTAs, FTAAs, and Head Refs trying to verify which points were granted after a match without backtracking on the FMS PC.

**Comment by JustDerek1** [comment]
So the detailed match info is on an alliance basis. On the team tab, we know which alliance is associated with the team we are viewing for that match.  On the event tab, we do not know which alliance the user wants to view. 

So, there are two potential solutions

1) have the detailed view list info for both alliances simultaneously. 

2) if the user taps on the blue side it brings up the blue alliance and vice versa for the red.  This could cause confusion unless I shade the screen to be appropriately blue or red. 

Thoughts?

**Comment by Jpatterson780** [comment]
Good point, not sure why that didn't cross my mind. 
From a volunteer perspective, I would lean towards displaying detailed information for both alliances simultaneously. While the option of taping on the respective side would potentially cut clutter and reduce the amount of information displayed at one time, it does seem like an additional point of confusion. 
For my intended use of the application as a volunteer, it actually makes the most sense to view both alliances together.

**Comment by JustDerek1** [comment]
Ok, I need to work on that detailed screen when the new competition is announced.  I will evaluate if/how I can display both alliance scores simultaneously or maybe have a button to flip between the views.

That's one of the few screens that I will need to update on a year-to-year basis.  Great feedback!

**Comment by jpatterson780** [comment]
I can assure you, those of use working field side in key volunteer positions would definitely appreciate that functionality. I'd be glad to continue collaborating more in depth on that aspect if needed! Additionally, I'll inquire about discussion some of the game details with you before kickoff, which could give you a jump start on the update for this season. That'd required a you sign a non-disclosure of course! But that'd at least allow you to get an updated app version ready for kickoff day!

**Comment by jpatterson780** [comment]
I should add, that the chances, however, are not likely. All I can do is ask HQ if this circumstance would warrant releasing information to you.

**Comment by JustDerek1** [comment]
Ok, with Beta 81, there is a new detailed screen!  Based on your comment above, it gives detailed information for BOTH alliances at the same time - for easy comparison.  This is currently only available when tapping on an event and then selecting a match in the Matches area.  (I will probably hook it up to the matches list in the Team tab as well (once it is debugged).

Hopefully this helps as a volunteer.  Also, please remember that detailed score information will probably take several minutes after it is published from the ref/judges table.
