### ISSUE TITLE
Notifications do not work for new blog posts. 

### ISSUE THREAD

**Issue by nardavin** [JustDerek1/FRCCentralIssues#32]
Notifications for blog posts are turned on in both the app and system settings, but I did not get a push notification with the new blog post.

**Comment by JustDerek1** [comment]
I submitted this myself earlier today as I noticed yesterday that this was not working.  Excellent catch!

This is going to take some real digging.  I poked around for about 2 hours last night to figure out why it stopped working.  It was not immediately apparent.  This absolutely must be fixed before it goes live and will probably take a few weeks.  I'll have to do a deep dive.  

I'm going to close the one that I opened earlier as a duplicate.  Thanks!

**Comment by nardavin** [comment]
It appears that the issue is fixed. I'll leave it up to you to close this thread if you believe the issue is truly fixed, but I have been receiving notifications for the last few blog posts.

**Comment by JustDerek1** [comment]
Ok, that’s just weird.  I didn’t change anything and it is working again for you.  I’ll test it on my end as well and make sure.

Thanks!
Derek

**Comment by JustDerek1** [comment]
This should be fixed now.
