### ISSUE TITLE
Some team lists not populating for 2017 events

### ISSUE THREAD

**Issue by nardavin** [JustDerek1/FRCCentralIssues#33]
Some events are not populating with the teams attending. This data is available on TBA, it is just not showing in the app. One example is Arizona West. TPG is having the same issue, so it is not user specific.

**Comment by JustDerek1** [comment]
This helps.  It is almost certainly a data issue.  I will check into it.  It really helps to have the detail that you provided about which event you were viewing.  Thanks!

**Comment by JustDerek1** [comment]
Thank you very much for letting me know which event.  That helps.  

Could you go into the event, view the team list and pull down on the table to refresh it?  OR, use the refresh button at the top of the Event Detail screen (it will attempt to refresh all data).  Please let me know if it still does not list the teams.

**Comment by JustDerek1** [comment]
Ok, this should be fixed again!
