### ISSUE TITLE
Favouriting Events in Search

### ISSUE THREAD

**Issue by brendanarciszewski** [JustDerek1/FRCCentralIssues#34]
When I favourite an event on the search screen, the event doesn't show up as favourites on the events screen. However when I unfavourite an event on the search screen, the expected behaviour occurs.

**Comment by JustDerek1** [comment]
Are you on an iPad?  If so, I think I've replicated it.  It doesn't appear to refresh properly.  On the iPhone, I believe it works just fine.  Definitely a bug.  Thanks!

**Comment by brendanarciszewski** [comment]
I have the problem on my iPhone 4s (iOS 9) and iPad Air (iOS 10.2).

**Comment by JustDerek1** [comment]
I’ll keep digging.  I can replicate it on my iPad, but not the iPhone - it refreshes just fine on my iPhone.  The solution that I would put in place for this would work for both the iPhone and iPad anyway.

Derek

**Comment by JustDerek1** [comment]
Ok, this will be fixed in the next beta.
