### ISSUE TITLE
Twitter Event Feed

### ISSUE THREAD

**Issue by brendanarciszewski** [JustDerek1/FRCCentralIssues#35]
The Twitter tab on an individual event screen displays all tweets from from the FRC Twitter account. I thought it was meant for tweets hashtagged with the event's code.

**Comment by JustDerek1** [comment]
Brendan,

It is generic right now.  The Blue Alliance does not publish Twitter handles for an event.  If they did, I could get the data from TBA.  FIRST also does not provide Twitter handles for events.

So, there are options:

1)  Leave it the way it is for Version 1.0.

2)  Take it off for Version 1.0.

Then for Version 2.0:

1)  Leave it the way it is (definitely not optimal)

2)  Ask users for the Twitter handle for the event.  If they know it and submit it, then the administrator (me to start with) would have to approve it.  Once approved, it would appear as the default for that event.

3)  Allow users to enter a handle, do not store it in the cloud, but only make it available for their own use within the app.

Other solutions?

Thoughts?

Derek

**Comment by brendanarciszewski** [comment]
I thought the standard hashtag was just the #frc[event code]. For example, last year's Greater Toronto Central Regional and this year's Victoria Park District event are #frconto2

**Comment by JustDerek1** [comment]
Ok, that would be easy.  I just didn’t think that people knew their event codes to tweet like that.  Very cool.

Derek

**Comment by JustDerek1** [comment]
This is done and will appear in the next beta release.
