### ISSUE TITLE
Team Count in Event

### ISSUE THREAD

**Issue by brendanarciszewski** [JustDerek1/FRCCentralIssues#36]
The info tab for both Buckeye and Greater Toronto Central (2016 events) displays total teams as zero. I have not see this issue with any 2017 events.

**Comment by brendanarciszewski** [comment]
In fact, teams are not loading for those events.

**Comment by JustDerek1** [comment]
Yep - new bug due to the new backend.  Fixed.  It should actually be fixed now - no new beta needed.  So you can check it out.  This would have been failing for many of the 2017 events.
