### ISSUE TITLE
Odd Text in Event Info

### ISSUE THREAD

**Issue by brendanarciszewski** [JustDerek1/FRCCentralIssues#37]
Clicking on the pin reveals what looks like some code.
Also, the "Please double check!" text is cutoff on my iPhone 4s after "Please"
![img_0301](https://cloud.githubusercontent.com/assets/20262406/21359549/9666d1dc-c6aa-11e6-8114-d8fe441a7b26.PNG)

**Comment by JustDerek1** [comment]
This is fixed in the next beta release.  Great catch!
