### ISSUE TITLE
Photos don't load consistently for teams

### ISSUE THREAD

**Issue by JustDerek1** [JustDerek1/FRCCentralIssues#6]
Photos for 781 don't seem to load, and no indicator is shown that images are reloading when I click the reload button after clicking the photo (it doesn't need to be obvious, just somewhere it should be shown that content is downloading) (Brendan, The Mac Man, & Mark)

**Comment by devyntk** [comment]
Same thing here. 1982 has no featured photo, yet has an image in TBA. Usually doesn't load.

**Comment by ndalporto** [comment]
Same with 5940, however I was able to see photo from 254 when I went to their page.

**Comment by brendanarciszewski** [comment]
This is not a problem for me anymore.

**Comment by JustDerek1** [comment]
So, photos do not automatically load over cellular - even if the setting is turned on.  One of the bugs is that downloading over cellular doesn't work.  Another bug that I've seen is that it does not download the default image.  If you go into the image viewer and tap refresh, it doesn't always pull down the additional photos either.  Photos are a bit flakey for some reason.  So, I'm going to leave this open to just watch this a bit.

**Comment by JustDerek1** [comment]
So, I tracked down a couple bugs around loading images.  It was not always loading images consistently.  It should be much better now.

**Comment by JustDerek1** [comment]
Oh, this is fixed in Beta 82.
